name: Testing & Coverage
on: [pull_request, push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pdm install

      - name: Test & publish code coverage
        run: |
          pdm run test-coverage
      - uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: pdm run coverage
          debug: true
